import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test, { after } from "node:test";
import mysql, { type RowDataPacket } from "mysql2/promise";
import { createPersistence } from "../main/persistence.js";
import { runMigrations } from "../migrations/migration-runner.js";
import type { MigrationPool } from "../migrations/migration-state.js";
import { createCustodyRequestUseCases } from "../modules/warehouse/application/custody-request.use-cases.js";
import { createWarehouseUseCases } from "../modules/warehouse/application/warehouse.use-cases.js";
import { createNotificationEmailQueue } from "../modules/notifications/application/notification-email.queue.js";
import { createNotificationEmailWorker } from "../modules/notifications/application/notification-email.worker.js";
import { createPrivateMediaStorage } from "../shared/infrastructure/private-media-storage.js";
import { createServices } from "../main/services.js";
import { createApp } from "../main/app.js";
import { pool as defaultPool } from "../main/database.js";
import { createAuthSecurity } from "../modules/auth/infrastructure/auth-security.js";
import { env } from "../shared/infrastructure/config/env.js";
import { once } from "node:events";
import type { AddressInfo } from "node:net";
import { preflightMigrations } from "../migrations/migration-preflight.js";

after(async () => { await defaultPool.end(); });

test("isolated MySQL custody: authorization, concurrency, lifecycle, proof and notifications", { skip: process.env.LNFS_DB_INTEGRATION !== "1" }, async t => {
  const host = process.env.LNFS_TEST_DB_HOST;
  if (host !== "127.0.0.1" || !process.env.LNFS_TEST_DB_NAME?.endsWith("_test")) throw new Error("Only explicit isolated loopback *_test databases allowed");
  const config = { host, port: Number(process.env.LNFS_TEST_DB_PORT), user: process.env.LNFS_TEST_DB_USER, password: process.env.LNFS_TEST_DB_PASSWORD, multipleStatements: true, timezone: "Z", connectionLimit: 8 };
  const name = `lnfs_custody_${randomUUID().replaceAll("-", "")}_test`;
  const admin = mysql.createPool(config);
  await admin.query(`CREATE DATABASE \`${name}\``);
  const pool = mysql.createPool({ ...config, database: name });
  const uploadDir = await mkdtemp(path.join(os.tmpdir(), "lnfs-private-proof-"));
  try {
    await runMigrations({ directory: fileURLToPath(new URL("../migrations/", import.meta.url)), pool: pool as unknown as MigrationPool, log: () => {} });
    const p = createPersistence(pool);
    const ids = { finder: randomUUID(), owner: randomUUID(), outsider: randomUUID(), staff: randomUUID(), approver: randomUUID(), found: randomUUID(), lost: randomUUID(), claim: randomUUID(), room: randomUUID() };
    for (const user of [ids.finder,ids.owner,ids.outsider,ids.staff,ids.approver]) {
      await pool.execute("INSERT INTO users (id,email,normalized_email,password_hash,full_name,email_verified_at) VALUES (?,?,?,?,?,UTC_TIMESTAMP())", [user,`${user}@example.invalid`,`${user}@example.invalid`,"test-only","Fixture"]);
      await pool.execute("INSERT INTO user_roles (user_id,role_code) VALUES (?,?)", [user,ids.approver === user ? "ADMIN" : ids.staff === user ? "STAFF" : "STUDENT"]);
    }
    const [points] = await pool.query<RowDataPacket[]>("SELECT id FROM handover_points WHERE is_active = TRUE LIMIT 1");
    const point = String(points[0].id);
    const [categories] = await pool.query<RowDataPacket[]>("SELECT id FROM item_categories WHERE name LIKE '%Chìa%' LIMIT 1");
    const categoryId = categories[0]?.id ? String(categories[0].id) : randomUUID();
    if (!categories.length) await pool.execute("INSERT INTO item_categories (id,name,name_normalized) VALUES (?,'Chìa khóa','chia khoa')", [categoryId]);
    for (const [post,user,type] of [[ids.found,ids.finder,"FOUND"],[ids.lost,ids.owner,"LOST"]]) await pool.execute("INSERT INTO posts (id,user_id,type,title,title_normalized,description,description_normalized,category_id) VALUES (?,?,?,'Keys','keys','Fixture keys','fixture keys',?)", [post,user,type,categoryId]);
    await pool.execute("INSERT INTO claims (id,post_id,claimant_id,status,finder_decision) VALUES (?,?,?,'CONVERSATION_OPEN','ACCEPTED')", [ids.claim,ids.found,ids.owner]);
    await pool.execute("INSERT INTO claim_participants (claim_id,user_id,participant_role,consent_status) VALUES (?,?,'FINDER','ACCEPTED'), (?,?,'CLAIMANT','ACCEPTED')", [ids.claim,ids.finder,ids.claim,ids.owner]);
    await pool.execute("INSERT INTO chat_rooms (id,claim_id) VALUES (?,?)", [ids.room,ids.claim]);
    const queue = createNotificationEmailQueue({ repository: p.notificationEmailRepository, id: randomUUID, chatDelayMinutes: 5, digestDelayMinutes: 15 });
    const delivery = { notificationRepository: p.notificationRepository, notificationEmailQueue: queue };
    const custody = createCustodyRequestUseCases({ custodyRequestRepository: p.custodyRequestRepository, warehouseRepository: p.warehouseRepository, ...delivery, withTransaction: p.transaction, id: randomUUID });
    const warehouse = createWarehouseUseCases({ warehouseRepository: p.warehouseRepository, custodyRequestRepository: p.custodyRequestRepository, proofStorage: createPrivateMediaStorage({ uploadDir, namespace: "warehouse-proof", invalidPathMessage: "Invalid", notFoundMessage: "Missing" }), ...delivery, withTransaction: p.transaction, id: randomUUID });
    const input = { postId: ids.found, claimId: ids.claim, roomId: ids.room, handoverPointId: point, reason: "Private note never belongs in notifications", idempotencyKey: "a".repeat(190) };
    await t.test("rejects forged, empty, LOST and cross-user idempotent requests", async () => {
      await assert.rejects(custody.createRequest(input, ids.outsider));
      await assert.rejects(custody.createRequest({}, ids.finder));
      await assert.rejects(custody.createRequest({ ...input, intakeType: "WALK_IN" }, ids.finder));
      await assert.rejects(custody.createRequest({ ...input, postId: ids.lost }, ids.owner));
      await assert.rejects(custody.createRequest({ ...input, roomId: randomUUID() }, ids.finder));
    });
    const [first,second] = await Promise.all([custody.createRequest(input,ids.finder),custody.createRequest(input,ids.finder)]);
    assert.equal(first.request.id,second.request.id);
    await assert.rejects(custody.createRequest({ ...input, reason: "Different" },ids.finder));
    await assert.rejects(custody.getRequest(first.request.id,ids.outsider));
    await t.test("cancel releases room escalation; request can be recreated", async () => {
      await pool.execute("UPDATE chat_rooms SET escalated_at = UTC_TIMESTAMP() WHERE id = ?", [ids.room]);
      await custody.cancelRequest(first.request.id,{ reason: "Finder cancelled" },ids.finder);
      const [rows] = await pool.query<RowDataPacket[]>("SELECT escalated_at FROM chat_rooms WHERE id = ?", [ids.room]);
      assert.equal(rows[0].escalated_at,null);
    });
    const next = await custody.createRequest({ ...input, idempotencyKey: "new-request-key" },ids.finder);
    assert.equal(next.request.status, "PENDING");
    assert.equal((await custody.createRequest({ ...input, idempotencyKey: "new-request-key" },ids.finder)).request.id, next.request.id);
    await assert.rejects(custody.confirmIntake(next.request.id,{ conditionNotes: "Good", confirmedHandoverAt: new Date(Date.now()+3600000) },ids.staff));
    const receivedAt = new Date(Date.now()-60000);
    const [intake,retry] = await Promise.all([custody.confirmIntake(next.request.id,{ conditionNotes: "Good", confirmedHandoverAt: receivedAt },ids.staff),custody.confirmIntake(next.request.id,{ conditionNotes: "Good", confirmedHandoverAt: receivedAt },ids.staff)]);
    assert.equal(intake?.warehouseItemId,retry?.warehouseItemId);
    const itemId = intake!.warehouseItemId!;
    const [items] = await pool.query<RowDataPacket[]>("SELECT * FROM warehouse_items WHERE post_id = ?", [ids.found]);
    assert.equal(items.length,1);
    assert.equal(items[0].status,"RECEIVED");
    assert.equal((items[0].retention_deadline.getTime()-items[0].received_at.getTime())/86400000,120);
    const [post] = await pool.query<RowDataPacket[]>("SELECT status FROM posts WHERE id = ?", [ids.found]);
    assert.equal(post[0].status,"OPEN");
    await assert.rejects(custody.cancelRequest(next.request.id,{},ids.finder));
    for (const status of ["RETURNED","CLAIMED","DISPOSED","DONATED","TRANSFERRED"] as const) await assert.rejects(warehouse.updateItem(itemId,{ status },ids.staff));
    await assert.rejects(warehouse.updateItem(itemId,{ status: "EXPIRED" },ids.staff));
    await t.test("canonical verified return uses private proof and opens existing feedback contract", async () => {
      const historyId = randomUUID();
      await pool.execute("INSERT INTO claim_audit_events (id,claim_id,actor_id,action,metadata_json) VALUES (?,?,?,'CUSTODY_ESCALATED',?)", [historyId,ids.claim,ids.finder,JSON.stringify({ decision: "ESCALATE_TO_CUSTODY" })]);
      assert.equal((await warehouse.returnClaimReviews(itemId,ids.staff)).claims[0].verified,false);
      const verification = { claimId: ids.claim, recipientId: ids.owner, verified: true, reason: "Checked private key engraving and recipient ID in person" };
      await assert.rejects(warehouse.verifyCustodyClaim(itemId,verification,ids.finder));
      await warehouse.legalHold(itemId,true,"Review pending",ids.approver);
      await assert.rejects(warehouse.verifyCustodyClaim(itemId,verification,ids.staff));
      await warehouse.legalHold(itemId,false,"Review cleared",ids.approver);
      await Promise.all([warehouse.verifyCustodyClaim(itemId,verification,ids.staff),warehouse.verifyCustodyClaim(itemId,verification,ids.staff)]);
      const [history] = await pool.query<RowDataPacket[]>("SELECT id,actor_id,action FROM claim_audit_events WHERE claim_id = ?", [ids.claim]);
      assert.ok(history.some(e => e.id === historyId && e.actor_id === ids.finder && e.action === "CUSTODY_ESCALATED"));
      assert.equal(history.filter(e => e.action === "STAFF_CUSTODY_VERIFIED").length,1);
      const [claimState] = await pool.query<RowDataPacket[]>("SELECT status,finder_decision FROM claims WHERE id = ?", [ids.claim]);
      assert.equal(claimState[0].status,"ACCEPTED");
      assert.equal(claimState[0].finder_decision,"ACCEPTED");
      assert.equal((await warehouse.returnRecipients(itemId,ids.staff)).recipients[0].recipientId,ids.owner);
      await warehouse.reserveItem(itemId,ids.claim,ids.owner,ids.staff);
      const buffer = Buffer.from([0xff,0xd8,0xff,0xe0]);
      const proof = await warehouse.uploadProof(itemId,{ buffer, size: buffer.length, mimetype: "image/jpeg" },ids.staff);
      assert.ok(!proof.url.includes("data:") && !proof.url.includes("cloudinary"));
      await assert.rejects(warehouse.getProof(proof.id,ids.outsider));
      assert.equal((await warehouse.getProof(proof.id,ids.staff)).body.length,4);
      const reportId = randomUUID();
      await p.transaction(db => p.reportRepository.create({ id: reportId, reporterId: ids.owner, target: { entityType: "CHAT", entityId: ids.room, sourceType: "MESSAGE", sourceId: randomUUID(), title: "Fixture", status: "ACCEPTED" }, reason: "Return dispute", details: null, idempotencyKey: randomUUID(), requestHash: "fixture" },db));
      await assert.rejects(warehouse.returnItem(itemId,{ claimId: ids.claim, recipientId: ids.owner, receiverName: "Fixture", receiverIdentity: "verified", receiverPhone: "0123456789", proofImage: proof.id },ids.staff));
      assert.equal((await p.warehouseRepository.findItemById(itemId))?.status,"CLAIMED");
      assert.equal((await p.warehouseRepository.findProof(proof.id,undefined))?.attached,false);
      await pool.execute("UPDATE reports SET status = 'REVIEWED' WHERE id = ?", [reportId]);
      const returned = await warehouse.returnItem(itemId,{ claimId: ids.claim, recipientId: ids.owner, receiverName: "Fixture", receiverIdentity: "verified", receiverPhone: "0123456789", proofImage: proof.id },ids.staff);
      assert.equal(returned?.status,"RETURNED");
      assert.equal((await warehouse.returnItem(itemId,{ claimId: ids.claim, recipientId: ids.owner, receiverName: "Fixture", receiverIdentity: "verified", receiverPhone: "0123456789", proofImage: proof.id },ids.staff))?.status,"RETURNED");
      await assert.rejects(warehouse.returnItem(itemId,{ claimId: ids.claim, recipientId: ids.outsider, receiverName: "Fixture", receiverIdentity: "verified", receiverPhone: "0123456789", proofImage: proof.id },ids.staff));
      const [completed] = await pool.query<RowDataPacket[]>("SELECT appointment_id FROM warehouse_completed_returns WHERE warehouse_item_id = ?", [itemId]);
      const feedback = await p.returnFeedbackRepository.findAppointmentForFeedback(String(completed[0].appointment_id));
      assert.equal(feedback?.status,"COMPLETED");
      assert.ok(feedback?.custodyAuthorizedAt);
      assert.equal(feedback?.claimantId,ids.owner);
      assert.equal(feedback?.finderId,ids.finder);
      assert.equal((await custody.createRequest({ ...input, idempotencyKey: "new-request-key" },ids.finder)).request.id,next.request.id);
      await assert.rejects(custody.createRequest({ ...input, idempotencyKey: "new-request-key", reason: "Changed after completion" },ids.finder));
    });
    const [messages] = await pool.query<RowDataPacket[]>("SELECT n.body,n.type,o.event_type FROM notifications n LEFT JOIN notification_email_outbox o ON o.notification_id = n.id WHERE n.entity_type = 'CUSTODY_REQUEST'");
    assert.ok(messages.length >= 8);
    assert.ok(messages.every(n => !String(n.body).includes(input.reason)));
    assert.ok(messages.filter(n => n.event_type).every(n => n.event_type === "CUSTODY"));
    await t.test("an expired undisposed walk-in can be returned with private evidence, but not under legal hold", async () => {
      const expired = await warehouse.createItem({ itemName: "Expired fixture", handoverPointId: point, conditionNotes: "Good", receivedAt: new Date(Date.now()-200*86400000) },ids.staff);
      await warehouse.updateItem(expired.id,{ status: "EXPIRED" },ids.staff);
      await assert.rejects(warehouse.updateItem(expired.id,{ status: "RETURNED" },ids.staff));
      const proof = await warehouse.uploadProof(expired.id,{ buffer: Buffer.from([0xff,0xd8,0xff,0xe0]), size: 4, mimetype: "image/jpeg" },ids.staff);
      const input = { receiverName: "Offline owner", receiverIdentity: "ID-123456", receiverPhone: "0359123456", proofImage: proof.id };
      await warehouse.legalHold(expired.id,true,"Check pending",ids.approver);
      await assert.rejects(warehouse.returnItem(expired.id,input,ids.staff));
      assert.equal((await p.warehouseRepository.findProof(proof.id,undefined))?.attached,false);
      await warehouse.legalHold(expired.id,false,"Check cleared",ids.approver);
      assert.equal((await warehouse.returnItem(expired.id,input,ids.staff))?.status,"RETURNED");
      assert.ok((await warehouse.listLogs(expired.id)).some(log => log.fromStatus === "EXPIRED" && log.toStatus === "RETURNED"));
    });
    await t.test("disposition requires separate Admin approval and rechecks legal hold, retention and disputes", async () => {
      await pool.execute("INSERT INTO user_roles (user_id,role_code) VALUES (?,'ADMIN')", [ids.finder]);
      const record = await warehouse.createItem({ itemName: "Unclaimed fixture", handoverPointId: point, conditionNotes: "Good", receivedAt: new Date(Date.now()-200*86400000) },ids.staff);
      await assert.rejects(warehouse.legalHold(record.id,true,"test hold",ids.staff));
      const approval = await warehouse.requestDisposition(record.id,"DONATED","No claim after retention",ids.approver);
      await assert.rejects(warehouse.executeDisposition(approval.approvalId,ids.staff));
      await assert.rejects(warehouse.approveDisposition(approval.approvalId,ids.staff));
      await assert.rejects(warehouse.approveDisposition(approval.approvalId,ids.approver));
      await warehouse.approveDisposition(approval.approvalId,ids.finder);
      await warehouse.legalHold(record.id,true,"test hold",ids.approver);
      await assert.rejects(warehouse.executeDisposition(approval.approvalId,ids.staff));
      assert.equal((await p.warehouseRepository.findItemById(record.id))?.status,"RECEIVED");
      assert.ok((await warehouse.listLogs(record.id)).some(log => log.note?.startsWith("DISPOSITION_DENIED")));
      await warehouse.legalHold(record.id,false,"released",ids.approver);
      await assert.rejects(warehouse.executeDisposition(approval.approvalId,ids.staff));
      const buffer = Buffer.from([0xff,0xd8,0xff,0xe0]);
      const proof = await warehouse.uploadProof(record.id,{ buffer, size: buffer.length, mimetype: "image/jpeg" },ids.staff);
      const disputePost = randomUUID(), disputeClaim = randomUUID(), disputeRoom = randomUUID(), reportId = randomUUID();
      await pool.execute("INSERT INTO posts (id,user_id,type,title,title_normalized,description,description_normalized) VALUES (?,?,'FOUND','Fixture','fixture','Fixture','fixture')", [disputePost,ids.finder]);
      await pool.execute("UPDATE warehouse_items SET post_id = ? WHERE id = ?", [disputePost,record.id]);
      await pool.execute("INSERT INTO claims (id,post_id,claimant_id,status) VALUES (?,?,?,'CANCELLED')", [disputeClaim,disputePost,ids.owner]);
      await pool.execute("INSERT INTO claim_participants (claim_id,user_id,participant_role,consent_status) VALUES (?,?,'FINDER','ACCEPTED'), (?,?,'CLAIMANT','ACCEPTED')", [disputeClaim,ids.finder,disputeClaim,ids.owner]);
      await pool.execute("INSERT INTO chat_rooms (id,claim_id) VALUES (?,?)", [disputeRoom,disputeClaim]);
      await p.transaction(db => p.reportRepository.create({ id: reportId, reporterId: ids.owner, target: { entityType: "CHAT", entityId: disputeRoom, sourceType: "MESSAGE", sourceId: randomUUID(), title: "Fixture", status: "CANCELLED" }, reason: "Unresolved dispute", details: null, idempotencyKey: randomUUID(), requestHash: "fixture" },db));
      await assert.rejects(warehouse.executeDisposition(approval.approvalId,ids.staff,[proof.id]));
      assert.equal((await p.warehouseRepository.findItemById(record.id))?.status,"RECEIVED");
      await pool.execute("UPDATE reports SET status = 'REVIEWED' WHERE id = ?", [reportId]);
      await warehouse.executeDisposition(approval.approvalId,ids.staff,[proof.id]);
      await warehouse.executeDisposition(approval.approvalId,ids.staff);
      assert.equal((await p.warehouseRepository.findItemById(record.id))?.status,"DONATED");
      const fresh = await warehouse.createItem({ itemName: "Fresh", handoverPointId: point, conditionNotes: "Good" },ids.staff);
      const freshApproval = await warehouse.requestDisposition(fresh.id,"DISPOSED","Fresh fixture",ids.approver);
      await warehouse.approveDisposition(freshApproval.approvalId,ids.finder);
      await assert.rejects(warehouse.executeDisposition(freshApproval.approvalId,ids.staff));
    });
    await t.test("real HTTP matching keeps inactive history, hides own LOST and preserves history on refresh", async () => {
      const source = randomUUID(), ownLost = randomUUID(), inactive = randomUUID(), deleted = randomUUID(), hidden = randomUUID();
      await pool.execute("INSERT INTO posts (id,user_id,type,title,title_normalized,description,description_normalized) VALUES (?,?,'FOUND','Fixture','fixture','Fixture','fixture')", [source,ids.finder]);
      await pool.execute("UPDATE posts SET category_id = ? WHERE id = ?", [categoryId,source]);
      for (const [post,user,status,deletedAt] of [[ownLost,ids.finder,"OPEN",null],[inactive,ids.owner,"RESOLVED",null],[deleted,ids.owner,"OPEN",new Date()],[hidden,ids.owner,"HIDDEN",null]]) {
        await pool.execute("INSERT INTO posts (id,user_id,type,title,title_normalized,description,description_normalized,status,deleted_at) VALUES (?,?,'LOST','Fixture','fixture','Fixture','fixture',?,?)", [post,user,status,deletedAt]);
        await pool.execute("INSERT INTO match_results (id,lost_post_id,found_post_id,total_score) VALUES (?,?,?,0.7)", [randomUUID(),post,source]);
      }
      const services = createServices(p,{ ...env, uploadDir });
      const token = createAuthSecurity(env).signAccessToken({ sub: ids.finder, email: `${ids.finder}@example.invalid`, roles: ["STUDENT","ADMIN"], sessionVersion: 0 });
      const server = createApp({ services, checkReadiness: async () => {} }).listen(0,"127.0.0.1");
      await once(server,"listening");
      try {
        const response = await fetch(`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/posts/${source}/matches`,{ headers: { Authorization: `Bearer ${token}` } });
        assert.equal(response.status,200);
        const payload = await response.json() as { results: Array<{ candidate: { id: string; status: string; } }> };
        assert.deepEqual(payload.results.map(result => result.candidate.id),[inactive]);
        assert.equal(payload.results[0].candidate.status,"RESOLVED");
        for (const [userId,role] of [[ids.finder,"ADMIN"],[ids.staff,"STAFF"],[ids.approver,"ADMIN"]]) {
          const reviewToken = createAuthSecurity(env).signAccessToken({ sub: userId, email: `${userId}@example.invalid`, roles: [role as "STAFF" | "ADMIN"], sessionVersion: 0 });
          const review = await fetch(`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/posts/${source}/matches?page=1&pageSize=1`,{ headers: { Authorization: `Bearer ${reviewToken}` } });
          assert.equal(review.status,200);
          const page = await review.json() as { total: number; hasMore: boolean; results: Array<{ candidate: { id: string } }> };
          assert.equal(page.total,1);
          assert.equal(page.hasMore,false);
          assert.deepEqual(page.results.map(result => result.candidate.id),[inactive]);
        }
        await services.matchingService.runForPost(source);
        assert.ok((await p.matchingRepository.listForPost(source,0.45)).some(match => match.lostPostId === inactive));
        const direct = await services.claimService.createDirectMessage(ids.owner,{ postId: ownLost, content: "Test", sourceFoundPostId: source }).catch(() => null);
        assert.equal(direct,null);
        const targetLost = randomUUID();
        await pool.execute("INSERT INTO posts (id,user_id,type,title,title_normalized,description,description_normalized,category_id) VALUES (?,?,'LOST','Keys','keys','Fixture','fixture',?)", [targetLost,ids.owner,categoryId]);
        const conversation = await services.claimService.createDirectMessage(ids.finder,{ postId: targetLost, content: "Synthetic message", sourceFoundPostId: source });
        const context = await p.claimRepository.findVerificationContext(conversation.claim.id);
        assert.equal(context?.foundPostId,source);
        assert.equal(conversation.claim.finderId,ids.finder);
        assert.equal(conversation.claim.claimantId,ids.owner);
      } finally { server.close(); await once(server,"close"); }
    });
    await t.test("outbox failure rolls back business event and reminders never mutate warehouse state", async () => {
      const found = randomUUID();
      await pool.execute("INSERT INTO posts (id,user_id,type,title,title_normalized,description,description_normalized,category_id) VALUES (?,?,'FOUND','Fixture','fixture','Fixture','fixture',?)", [found,ids.outsider,categoryId]);
      const failing = createCustodyRequestUseCases({ custodyRequestRepository: p.custodyRequestRepository, warehouseRepository: p.warehouseRepository,
        notificationRepository: p.notificationRepository, notificationEmailQueue: { ...queue, enqueue: async () => { throw new Error("Injected outbox failure"); } }, withTransaction: p.transaction, id: randomUUID });
      await assert.rejects(failing.createRequest({ postId: found, handoverPointId: point },ids.outsider), /Injected outbox failure/);
      const [failed] = await pool.query<RowDataPacket[]>("SELECT id FROM custody_requests WHERE post_id = ?", [found]);
      assert.equal(failed.length,0);
      const request = await custody.createRequest({ postId: found, handoverPointId: point, idempotencyKey: input.idempotencyKey },ids.outsider);
      await custody.acceptRequest(request.request.id,{ handoverPointId: point },ids.staff);
      const intake = await custody.confirmIntake(request.request.id,{ conditionNotes: "Good", confirmedHandoverAt: new Date(Date.now()-200*86400000) },ids.staff);
      const proof = await warehouse.uploadProof(intake!.warehouseItemId!,{ buffer: Buffer.from([0xff,0xd8,0xff,0xe0]), size: 4, mimetype: "image/jpeg" },ids.staff);
      await pool.execute("UPDATE warehouse_private_proofs SET created_at = UTC_TIMESTAMP() - INTERVAL 4 DAY WHERE id = ?", [proof.id]);
      await warehouse.runMaintenance();
      await warehouse.runMaintenance();
      assert.equal((await p.warehouseRepository.findItemById(intake!.warehouseItemId!))?.status,"RECEIVED");
      await assert.rejects(warehouse.getProof(proof.id,ids.staff));
      const [notifications] = await pool.query<RowDataPacket[]>("SELECT user_id,COUNT(*) AS total FROM notifications WHERE type = 'CUSTODY_OVERDUE' AND entity_id = ? GROUP BY user_id", [request.request.id]);
      assert.ok(notifications.length > 0);
      assert.ok(notifications.every(row => Number(row.total) === 1));
    });
    await t.test("two email workers cannot reclaim a slow or expired SMTP attempt", async () => {
      await pool.execute("UPDATE notification_email_outbox SET status = 'CANCELLED'");
      const enqueue = async () => {
        const outboxId = randomUUID();
        await p.transaction(async db => {
          const n = await p.notificationRepository.create({ userId: ids.owner, type: "CUSTODY_UPDATED", title: "Fixture", entityType: "POST", entityId: ids.found },db);
          await p.notificationEmailRepository.enqueue({ id: outboxId, notificationId: n!.id, recipientUserId: ids.owner, eventType: "CUSTODY", entityType: "POST", entityId: ids.found, roomId: null, deliveryMode: "IMMEDIATE", idempotencyKey: outboxId, dueAt: new Date(Date.now()-1000) },db);
        });
        return outboxId;
      };
      const outboxId = await enqueue();
      let sends = 0;
      let start!: () => void, finish!: () => void;
      const started = new Promise<void>(resolve => { start = resolve; });
      const blocked = new Promise<void>(resolve => { finish = resolve; });
      const options = { repository: p.notificationEmailRepository, emailDelivery: { send: async () => { sends++; start(); await blocked; return {}; } }, id: randomUUID, frontendUrl: "https://lnfs.example.invalid", logger: { warn() {} }, leaseSeconds: 3 };
      const first = createNotificationEmailWorker(options).runOnce(1);
      try {
        await started;
        await new Promise(resolve => setTimeout(resolve,4000));
        await createNotificationEmailWorker(options).runOnce(1);
        assert.equal(sends,1);
      } finally { finish(); await first; }
      const [sent] = await pool.query<RowDataPacket[]>("SELECT status FROM notification_email_outbox WHERE id = ?", [outboxId]);
      assert.equal(sent[0].status,"SENT");
      const expiredId = await enqueue(), oldToken = randomUUID();
      await p.notificationEmailRepository.claimDue({ limit: 1, leaseToken: oldToken, leaseSeconds: 3 });
      await pool.execute("UPDATE notification_email_outbox SET lease_expires_at = UTC_TIMESTAMP() - INTERVAL 1 SECOND WHERE id = ?", [expiredId]);
      assert.deepEqual(await p.notificationEmailRepository.claimDue({ limit: 1, leaseToken: randomUUID(), leaseSeconds: 3 }),[]);
      assert.equal(await p.notificationEmailRepository.renewLease(oldToken,3),false);
      await p.notificationEmailRepository.markSent(oldToken);
      await p.notificationEmailRepository.releaseLeaseForRetry({ leaseToken: oldToken, dueAt: new Date(), errorCode: "EAUTH" });
      const [expired] = await pool.query<RowDataPacket[]>("SELECT status,last_error_code FROM notification_email_outbox WHERE id = ?", [expiredId]);
      assert.equal(expired[0].status,"CANCELLED");
      assert.equal(expired[0].last_error_code,"SMTP_LEASE_EXPIRED_UNCERTAIN");
    });
    await t.test("recovered legacy 053 is not an alias and unknown checksums stay blocked", async () => {
      const version = "053_custody_and_guarded_disposition.sql";
      const checksum = "63b1268a45409de6b4b12eb7473a3e5254459bd9da0e4db1c0c3497d9e4c4eef";
      await pool.execute("INSERT INTO schema_migrations (version,checksum) VALUES (?,?)", [version,checksum]);
      await pool.execute("DELETE FROM schema_migrations WHERE version = '053_custody_requests.sql'");
      await pool.execute("DELETE FROM schema_migration_attempts WHERE version = '053_custody_requests.sql'");
      const preflight = await preflightMigrations({ directory: fileURLToPath(new URL("../migrations/",import.meta.url)), pool: pool as unknown as MigrationPool });
      assert.ok(preflight.pending.includes("053_custody_requests.sql"));
      assert.equal(preflight.warnings.length,1);
      await runMigrations({ directory: fileURLToPath(new URL("../migrations/",import.meta.url)), pool: pool as unknown as MigrationPool, log: () => {} });
      const [rows] = await pool.query<RowDataPacket[]>("SELECT checksum FROM schema_migrations WHERE version = ?", [version]);
      assert.equal(rows[0].checksum,checksum);
      await pool.execute("UPDATE schema_migrations SET checksum = ? WHERE version = ?", ["f".repeat(64),version]);
      await assert.rejects(preflightMigrations({ directory: fileURLToPath(new URL("../migrations/",import.meta.url)), pool: pool as unknown as MigrationPool }));
    });
  } finally {
    await pool.end();
    await admin.query(`DROP DATABASE \`${name}\``);
    await admin.end();
    await rm(uploadDir,{ recursive: true, force: true });
  }
});
