CREATE TABLE IF NOT EXISTS return_feedback (
  id CHAR(36) PRIMARY KEY,
  appointment_id CHAR(36) NOT NULL,
  claim_id CHAR(36) NOT NULL,
  post_id CHAR(36) NOT NULL,
  reviewer_id CHAR(36) NOT NULL,
  target_user_id CHAR(36) NOT NULL,
  rating TINYINT NOT NULL,
  comment VARCHAR(1000) NULL,
  is_negative BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('NEW', 'REVIEWED', 'FLAGGED', 'DISMISSED') NOT NULL DEFAULT 'NEW',
  reviewed_by CHAR(36) NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_return_feedback_appointment_reviewer (appointment_id, reviewer_id),
  KEY idx_return_feedback_status_created (status, created_at),
  KEY idx_return_feedback_target (target_user_id),
  CONSTRAINT fk_return_feedback_appointment FOREIGN KEY (appointment_id) REFERENCES return_appointments(id),
  CONSTRAINT fk_return_feedback_claim FOREIGN KEY (claim_id) REFERENCES claims(id),
  CONSTRAINT fk_return_feedback_post FOREIGN KEY (post_id) REFERENCES posts(id),
  CONSTRAINT fk_return_feedback_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id),
  CONSTRAINT fk_return_feedback_target FOREIGN KEY (target_user_id) REFERENCES users(id),
  CONSTRAINT fk_return_feedback_reviewer_admin FOREIGN KEY (reviewed_by) REFERENCES users(id),
  CONSTRAINT chk_return_feedback_rating CHECK (rating BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
