CREATE TABLE IF NOT EXISTS campus_radar_events (
  id CHAR(36) PRIMARY KEY,
  event_type ENUM('ACADEMIC', 'SPORTS', 'CULTURAL', 'CAMPUS_OPERATIONS', 'WEATHER', 'OTHER') NOT NULL,
  source_type ENUM('OFFICIAL_CALENDAR', 'CAMPUS_NOTICE', 'SECURITY_LOG', 'WEATHER_BULLETIN') NOT NULL,
  source_reference VARCHAR(255) NOT NULL,
  area_id CHAR(36) NULL,
  building_id CHAR(36) NULL,
  starts_at DATETIME NOT NULL,
  ends_at DATETIME NOT NULL,
  status ENUM('ACTIVE', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  created_by CHAR(36) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_campus_radar_events_area FOREIGN KEY (area_id) REFERENCES campus_areas(id),
  CONSTRAINT fk_campus_radar_events_building FOREIGN KEY (building_id) REFERENCES campus_buildings(id),
  CONSTRAINT fk_campus_radar_events_creator FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT chk_campus_radar_event_time CHECK (ends_at > starts_at),
  KEY idx_campus_radar_events_status_time (status, starts_at, ends_at),
  KEY idx_campus_radar_events_location_time (area_id, building_id, starts_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS campus_radar_alerts (
  id CHAR(36) PRIMARY KEY,
  event_id CHAR(36) NOT NULL,
  fingerprint CHAR(64) NOT NULL,
  detector_version VARCHAR(40) NOT NULL,
  category_id CHAR(36) NULL,
  window_start DATETIME NOT NULL,
  window_end DATETIME NOT NULL,
  window_minutes SMALLINT UNSIGNED NOT NULL,
  step_minutes SMALLINT UNSIGNED NOT NULL,
  baseline_start DATETIME NOT NULL,
  baseline_end DATETIME NOT NULL,
  baseline_window_count INT UNSIGNED NOT NULL,
  observed_count INT UNSIGNED NOT NULL,
  expected_mean DECIMAL(12,4) NOT NULL,
  standard_deviation DECIMAL(12,4) NOT NULL,
  z_score DECIMAL(12,4) NOT NULL,
  observed_ratio DECIMAL(12,4) NOT NULL,
  severity ENUM('WATCH', 'WARNING', 'CRITICAL') NOT NULL,
  status ENUM('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED') NOT NULL DEFAULT 'OPEN',
  occurrence_count INT UNSIGNED NOT NULL DEFAULT 1,
  emission_count INT UNSIGNED NOT NULL DEFAULT 1,
  last_detected_at DATETIME NOT NULL,
  last_emitted_at DATETIME NOT NULL,
  cooldown_until DATETIME NOT NULL,
  disposition_reason ENUM('REVIEWED_NO_ACTION', 'MONITORING', 'OPERATIONAL_FOLLOW_UP', 'FALSE_POSITIVE') NULL,
  disposition_by CHAR(36) NULL,
  disposition_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_campus_radar_alerts_event FOREIGN KEY (event_id) REFERENCES campus_radar_events(id),
  CONSTRAINT fk_campus_radar_alerts_category FOREIGN KEY (category_id) REFERENCES item_categories(id),
  CONSTRAINT fk_campus_radar_alerts_disposition_user FOREIGN KEY (disposition_by) REFERENCES users(id),
  CONSTRAINT chk_campus_radar_alert_window CHECK (window_end > window_start),
  UNIQUE KEY uq_campus_radar_alert_fingerprint (fingerprint),
  KEY idx_campus_radar_alerts_status_severity (status, severity, last_detected_at),
  KEY idx_campus_radar_alerts_event_category (event_id, category_id),
  KEY idx_campus_radar_alerts_cooldown (cooldown_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS campus_radar_audit_logs (
  id CHAR(36) PRIMARY KEY,
  event_id CHAR(36) NULL,
  alert_id CHAR(36) NULL,
  actor_id CHAR(36) NOT NULL,
  action ENUM('EVENT_CREATED', 'EVENT_ANALYZED', 'ALERT_EMITTED', 'ALERT_REFRESHED', 'ALERT_STATUS_CHANGED') NOT NULL,
  metadata JSON NULL,
  request_id VARCHAR(128) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_campus_radar_audit_event FOREIGN KEY (event_id) REFERENCES campus_radar_events(id),
  CONSTRAINT fk_campus_radar_audit_alert FOREIGN KEY (alert_id) REFERENCES campus_radar_alerts(id),
  CONSTRAINT fk_campus_radar_audit_actor FOREIGN KEY (actor_id) REFERENCES users(id),
  KEY idx_campus_radar_audit_event_created (event_id, created_at),
  KEY idx_campus_radar_audit_alert_created (alert_id, created_at),
  KEY idx_campus_radar_audit_actor_created (actor_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
