import { ArrowRight, MailCheck } from "lucide-react";
import { type FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../services/api";
import { AuthFrame } from "./login-page";

export function ForgotPasswordPage() {
  const [email, setEmail] = useState(""); const [error, setError] = useState(""); const [note, setNote] = useState(""); const [pending, setPending] = useState(false); const navigate = useNavigate();
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(""); try { const result = await api.forgotPassword(email); setNote(result.message); navigate(`/reset-password?email=${encodeURIComponent(email)}`, { state: { note: result.message } }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể gửi yêu cầu"); } finally { setPending(false); } }
  return <AuthFrame eyebrow="KHÔI PHỤC TÀI KHOẢN" title="Lấy lại quyền truy cập" subtitle="Chúng tôi gửi mã xác nhận một lần đến email của bạn."><form onSubmit={submit} className="form-stack"><label className="input-field"><span>Email</span><input type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label>{note && <p className="form-note">{note}</p>}{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={pending}>{pending ? "Đang gửi..." : <>Gửi mã <MailCheck size={18} /></>}</button></form><p className="form-links centered"><Link to="/login">Quay lại đăng nhập</Link></p></AuthFrame>;
}

export function ResetPasswordPage() {
  const query = new URLSearchParams(window.location.search); const [email, setEmail] = useState(query.get("email") ?? ""); const [token, setToken] = useState(""); const [newPassword, setNewPassword] = useState(""); const [error, setError] = useState(""); const [note, setNote] = useState("Kiểm tra cả thư mục Spam/Quảng cáo. Mỗi lần gửi mã mới sẽ vô hiệu hóa mã trước đó."); const [pending, setPending] = useState(false); const navigate = useNavigate();
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(""); try { await api.resetPassword(email, token, newPassword); navigate("/login", { replace: true, state: { message: "Mật khẩu đã được cập nhật. Hãy đăng nhập lại." } }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể đặt lại mật khẩu"); } finally { setPending(false); } }
  async function resend() { setPending(true); setError(""); try { const result = await api.forgotPassword(email); setNote(result.message); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể gửi lại mã"); } finally { setPending(false); } }
  return <AuthFrame eyebrow="ĐẶT LẠI MẬT KHẨU" title="Tạo mật khẩu mới" subtitle="Mã OTP có hiệu lực trong thời gian giới hạn và chỉ dùng được một lần."><form onSubmit={submit} className="form-stack"><label className="input-field"><span>Email</span><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label className="input-field"><span>Mã OTP gồm 6 số</span><input inputMode="numeric" maxLength={6} value={token} onChange={(e) => setToken(e.target.value)} required /></label><label className="input-field"><span>Mật khẩu mới</span><input type="password" minLength={8} value={newPassword} onChange={(e) => setNewPassword(e.target.value)} required /></label>{note && <p className="form-note">{note}</p>}{error && <p className="form-error">{error}</p>}<button type="button" className="secondary-button" disabled={pending || !email} onClick={() => void resend()}>Gửi lại mã OTP</button><button className="primary-button" disabled={pending}>{pending ? "Đang cập nhật..." : <>Cập nhật mật khẩu <ArrowRight size={18} /></>}</button></form><p className="form-links centered"><Link to="/login">Quay lại đăng nhập</Link></p></AuthFrame>;
}
