import { BadgeCheck, Mail, PencilLine, Shield, UserRound } from "lucide-react";
import { type FormEvent, useState } from "react";
import { useAuth } from "../context/auth-context";

export function ProfilePage() {
  const { user, updateProfile } = useAuth(); const [editing, setEditing] = useState(false); const [form, setForm] = useState({ fullName: user?.fullName ?? "", studentCode: user?.studentCode ?? "", phoneNumber: user?.phoneNumber ?? "" }); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  if (!user) return null;
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { await updateProfile({ fullName: form.fullName, studentCode: form.studentCode || null, phoneNumber: form.phoneNumber || null }); setEditing(false); setNotice("Đã cập nhật hồ sơ."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể cập nhật hồ sơ"); } }
  return <section className="profile-layout"><div className="section-heading"><p className="eyebrow">TÀI KHOẢN</p><h1>Hồ sơ cá nhân</h1><p>Authentication Sprint 1 đã sẵn sàng. Các module Lost &amp; Found sẽ được ghép vào nền tảng này ở các sprint sau.</p></div><article className="identity-card"><div className="avatar">{user.fullName.split(" ").slice(-1)[0]?.slice(0, 1).toUpperCase()}</div><div><h2>{user.fullName}</h2><p><Mail size={16} /> {user.email}</p><span className="status-chip"><BadgeCheck size={15} /> Email đã xác thực</span></div><button className="secondary-button" onClick={() => { setEditing((current) => !current); setNotice(""); }}><PencilLine size={17} /> {editing ? "Hủy" : "Chỉnh sửa"}</button></article>{notice && <p className="form-note">{notice}</p>}{editing && <form className="profile-form" onSubmit={submit}><label className="input-field"><span>Họ và tên</span><input value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} required /></label><label className="input-field"><span>Mã sinh viên/nhân sự</span><input value={form.studentCode} onChange={(e) => setForm({ ...form, studentCode: e.target.value })} /></label><label className="input-field"><span>Số điện thoại</span><input value={form.phoneNumber} onChange={(e) => setForm({ ...form, phoneNumber: e.target.value })} /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button">Lưu thay đổi</button></form>}<div className="profile-grid"><article><UserRound size={21} /><p>Vai trò hệ thống</p><strong>{user.roles.join(" · ")}</strong></article><article><Shield size={21} /><p>Phân quyền</p><strong>{user.roles.includes("ADMIN") ? "Quản trị viên" : user.roles.includes("STAFF") ? "Nhân viên vận hành" : "Người dùng campus"}</strong></article></div></section>;
}
